language: php

php:
  - 7.1
  - 7.2
  - 7.3

sudo: false

cache:
  directories:
    - ${HOME}/.composer/cache

install:
  - travis_retry composer install --no-interaction --no-suggest

before_script:
  - cp .env.testing .env
  - mkdir -p build/logs
  - chmod -R 777 build/logs

script:
  - XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls

notifications:
  email: false
  slack:
    secure: CgVPas+nUpTJH2/+FKzrKFI0MN2CjND3W+1JUUXvzvgE1mDkU2EeNlws7K1PwUcMDaYoGzuTmrAZGrQq1/Z5+mk7eXaQauPrd37hOjHdGycOj2lZKCG5i1C6hvIIoxA/Eu0fAAPeB5Nyx1VyRSwjrZvPB4LAtdZpJ6WHvdw4CromPgNmhQ64UqNFZWZ8+rZ4StxLVeOFIkBm4dIUMogaTMy6HARmNNYdxXR7J0D0rkYTazpfqFjn/DOMOyBMMVC2dqJ/9uapRAG+XSeWo5neJhSm47hBKJi42u/s9C5twmkynvCFlVmNfgX6ep0Hw18OCjBGdPO7NvjoBvEle4sju30k7BTYhamTDTB1QeZ870sYL8HEUNjzBNhTwyf+S8dqklwmD1Y/JXyWDAA8Q1KyJb/JAMexfa18Z/R7WdSjVOUo+zDyEvdCRMBQMrDMCwSriwK2xaz5iVFZIgG3qSL2UID0a/z7qHnxK0dcNWpiUrQ8q6XCVZMfdIHmWpQ5KwsyvsFLqe55IaOD6Pqpo04LRvMHCoSo46nuuc6LjcPSKE9lWKt3KEvGdNy/NsNSutsku+BGnisaNyUf5UJL7Y4u8z8xS/PXMmBZcBijtuXv0blhtXQIJ2kBs68lje5EnRC5IcS875PMVLeKIfzBcI5fby+x89X6eT9nBrcp6nc4wCw=
